driver:
  require_chef_omnibus: <%= ENV.fetch("CHEF_VERSION", "latest") %>
  ssh_key: <%= File.expand_path("./test/support/keys/vagrant") %>
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.5
  - name: fedora-20

suites:
  - name: default
    run_list:
      - recipe[cmake]
  - name: source
    run_list:
      - recipe[build-essential]
      - recipe[cmake]
    attributes:
      cmake:
        install_method: source
        source:
          version: 2.8.12.2
